---
- name: APT configuration and upgrade
  ansible.builtin.import_tasks: apt.yaml
  tags: upgrade

- name: Regional settings (locale, keyboard, timezone)
  ansible.builtin.import_tasks: regional.yaml
  tags: regional

- name: Autologin configuration
  ansible.builtin.import_tasks: autologin.yaml
  tags: autologin

- name: XFCE power and screensaver settings
  ansible.builtin.import_tasks: xfce.yaml
  tags: xfce

- name: Home directory cleanup
  ansible.builtin.import_tasks: cleanup.yaml
  tags: cleanup

- name: Enable shared folders
  ansible.builtin.import_tasks: shared_folder.yaml
  tags: shared_folder
